"""Initial version

Revision ID: 6b54a1283344
Revises: 
Create Date: 2024-05-04 17:21:50.905044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b54a1283344'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('magnet', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('preset', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('total_progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debrider_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debrider_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debrider_link',
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('is_unrestricted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.PrimaryKeyConstraint('link')
    )
    op.create_table('downloader_info',
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.PrimaryKeyConstraint('download_id')
    )
    op.create_table('downloader_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('download_id', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloader_task')
    op.drop_table('downloader_info')
    op.drop_table('debrider_link')
    op.drop_table('debrider_info')
    op.drop_table('debrider_file')
    op.drop_table('download')
    # ### end Alembic commands ###
