# TODO: push to ghcr
# TODO: test on arm (raspberry pi)
# TODO: tag latest on main branch
name: docker-image

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.HUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          #platforms: linux/amd64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ github.repository_owner }}/holerr:develop

      - name: Log in to ghcr.io
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}